### ISSUE TITLE
(Feature request) Button to delete the old bind directory

### ISSUE THREAD

**Issue by xizar** [emersonrp/bindcontrol#50] opened 2024-06-10 05:08 UTC
It would be nice if there was a function to delete all the old binds before writing the new ones, either as an on-demand button (delete now) or just before writing out bind files.

Your recent patch note about not writing unused MM binds if they're not set, suggests for people upgrading versions are going to have a lot of junk laying around.  While this doesn't necessarily hurt anything, it's unsightly.

Going forward, this will still be useful after respec'ing a character out of one travel power to another.  (For example, going from Teleportation to Flight, or Sorcery to Force of Will.)

**Comment by emersonrp** [comment] 2024-06-10 05:32
I've pondered this from time to time.  I've always shied away a little bit from deleting files programmatically because bugs in such code spell disaster.  That said, I might take a look at what it would take to do this safely, because I agree with the "unsightly" nature of leaving old unused files around.

**Comment by emersonrp** [comment] 2024-06-12 16:54
I'm leaning toward the tedious process of actually looking for each individual file BC might ever write, and deleting them one-by-one, instead of doing a scary directory-scale deletion.  This would also avoid deleting any other stuff people were intentionally keeping in their binds directory.  Over in #52 it came up obliquely that people might be keeping things like window state files in there.

**Comment by emersonrp** [comment] 2024-06-12 21:45
Starting in on this and already seeing some strange corner cases I'll need to handle -- if someone has a complex bind that they've written out, and then delete that custom bind from the profile, there's no trivial way to know about those files any more.  Will probably leverage the innards of this so that when deleting a custom bind, the (already implemented) confirmation box will have an "also delete all bindfiles" checkbox on it.

**Comment by emersonrp** [comment] 2024-06-13 21:23
Shipped some of the infrastructure to implement this with v0.18.0.5 -- nothing at all visible yet but it contains code to generate a list of all files that BindControl manages / writes.

This list can then eventually be used, in whole or in parts, to do targeted deletion of these files.

**Comment by emersonrp** [comment] 2024-06-14 05:10
![image](https://github.com/emersonrp/bindcontrol/assets/307232/d833632f-a758-4ae8-9860-2bd0bd71a15b)
 Does this seem like sane placement for a "Delete All Binds" button?

**Comment by xizar** [comment] 2024-06-14 06:44
I think so.

**Comment by emersonrp** [comment] 2024-06-14 17:17
OK, I have put out a prerelease that does this.  I'm still a little nervous about deleting things, but I've jumped through several hoops to try to prevent it from going rogue.  Please check it out carefully and let me know your luck.

https://github.com/emersonrp/bindcontrol/releases/tag/delete_binds_prerelease1

**Comment by xizar** [comment] 2024-06-14 18:36
I wonder how meaningful a list of bind files would be, to give some suggestion of what's responsible for what.  I have a flying blaster that has ~950 bind files written and a flying Mastermind (with pet binds) writing ~650 files, which seems odd.

**Comment by emersonrp** [comment] 2024-06-14 19:32
That list exists now, and could be surfaced.  For the Speed-on-Demand tab, the list is -thousands- of files long, as there are many permutations.  Without taking into consideration the small sprinkling of files that Complex Binds and Buffer Binds create, there's over 15000 possible files currently.  Still, I'm totally game to surface that info, maybe under the "Help" menu?  "Show this Tab's possible files"?  Or something?  Not sure what the cleanest way is to present that without being intrusive for the 99% case where people don't need or want to see that.

**Comment by emersonrp** [comment] 2024-06-14 19:37
Or, would it be helpful to present that info behind a "See Filenames" button on the "done writing binds" dialog?  I'm warming to that idea.

**Comment by xizar** [comment] 2024-06-14 22:55
Are user-friendly docs floating somewhere around that describe what each directory's for?  cbinds and mmbinds are kind of obvious, but an alternative to listing out all the 15k files, might be an explanation of the directory structure.

**Comment by emersonrp** [comment] 2024-06-14 22:58
I could make such a doc and stick it under the Help menu.  Also my notion of "See Filenames" would be showing only the few hundred that were written out.  I'll angle toward doing both.

**Comment by emersonrp** [comment] 2024-06-14 23:54
Added a high-level overview of the files/subdirs to the "Help" menu on the prerelease branch:

https://github.com/emersonrp/bindcontrol/releases/tag/delete_binds_prerelease2

Still pondering the format/etc of adding a list of what was written to the write-binds result dialog.  Could trivially just blat a big list of file paths into a scrolling text field, but it might be nice to format it a little bit for ease of reading.

**Comment by emersonrp** [comment] 2024-06-15 03:40
![image](https://github.com/emersonrp/bindcontrol/assets/307232/0e80937e-7b40-47fe-a745-59baea5d0ffa)
This is what I have so far.  Might just ship it as-is, though I think the dialog could use some reordering and wording updates.

**Comment by emersonrp** [comment] 2024-06-15 16:33
This has now officially shipped with v0.19.  Check it out.

https://github.com/emersonrp/bindcontrol/releases/tag/v0.19

**Comment by xizar** [comment] 2024-06-15 16:54
Some observations.

BindControl seems to have a list of files it has decided belong to it.

I loaded up a blaster profile and told it to delete binds straight away, without writing anything first.  BC had already decided it knew what files it controlled.

It did not delete the character's, now empty, directory.

I copied the binds from a mastermind and put it into the blaster's directory (without writing new binds or changing profiles), and told it to delete binds.  Bindcontrol deleted everything, including the non-blaster files (i.e., the MM pet binds).

I added a complex bind from within BC and deleting binds from within bc did not delete the cbinds folders or any of the files inside it that bc wrote.

**Comment by emersonrp** [comment] 2024-06-15 17:15
These are excellent observations, thanks.

> BindControl seems to have a list of files it has decided belong to it.

Yes just so.  The intent is to delete ALL possible binds, including debris left over from previous configurations (or bugs, like where the team select binds were being splatted out there unilaterally).

> It did not delete the character's, now empty, directory.

That's a bug, will investigate.  Assuming there's nothing left in there then yes, it should delete the profile directory.

> I copied the binds from a mastermind and put it into the blaster's directory (without writing new binds or changing profiles), and told it to delete binds. Bindcontrol deleted everything, including the non-blaster files (i.e., the MM pet binds).

Yeah, that's working as intended.  That's a bit of a pathological case, but you have the instincts of a software QA tester, hah.  The intended behavior of the feature is to clean out everything from the profile directory that BindControl might possibly have written, even if the Profile were configured differently previously.

What it -doesn't- do is just *BLAM* remove the whole populated directory, because (a) that's a scary thing to do programmatically, and (b) there might be things BindControl didn't write being kept in there.

> I added a complex bind from within BC and deleting binds from within bc did not delete the cbinds folders or any of the files inside it that bc wrote.

Oh that's also a bug.  Hmm, that -was- working, sigh.

Complex and Buffer Binds are weird cases and still need some work -- currently if you delete a Complex Bind from the profile, for instance, BindControl loses track of the files that bind originally wrote out.  There's no trivial way to fix that (without bloating the profile with historical cruft).  My intent is to make it so that deleting a Complex or Buffer Bind will offer, at that time, to delete all associated bind files.

**Comment by emersonrp** [comment] 2024-06-15 17:34
> I added a complex bind from within BC and deleting binds from within bc did not delete the cbinds folders or any of the files inside it that bc wrote.

I'm not seeing this behavior, it removes everything just fine for me.  I added a two-step Complex Bind, wrote out the binds, and then deleted all binds.  Both steps' files and the cbinds directory were correctly deleted.  Do you have a step-by-step to make this happen?  Thanks.

I have a fix for the profile directory not being removed and will ship a bugfix release shortly.

**Comment by emersonrp** [comment] 2024-06-15 17:41
https://github.com/emersonrp/bindcontrol/releases/tag/v0.19.0.1

**Comment by xizar** [comment] 2024-06-15 17:57
I tried reproducing it and wasn't able to, either.  I'm wondering if it was weirdness with file explorer not updating its window, as I was able to make a phantom version of the bug that persisted as long as I stayed in the cbind directory, but if I navigated out of it, it disappeared.

**Comment by emersonrp** [comment] 2024-06-15 18:04
OK cool.  I'll keep it at the back of my head but I -think- it's working correctly, modulo the business where you delete a custom bind and BindControl loses track of those files.  Could completely believe that having an Explorer window open inside cbinds could cause weirdness, possibly even Windows deciding that the directory is "in use" and disallowing it being removed, though it usually does the right thing in similar situations.

**Comment by emersonrp** [comment] 2024-06-15 21:47
OK, we now delete Complex and Buffer Binds' files on delete or rename of the associated bind.

I'm gonna close this issue since the spirit of "Keep the binds directory free of cruft" is now implemented, and we can open new issues if we find bugs in the implementation.

https://github.com/emersonrp/bindcontrol/releases/tag/v0.19.1

**Closed by emersonrp** 2024-06-15 21:47 UTC
Labels: enhancement
