### ISSUE TITLE
Window allocates too much vertical space (was: program window cannot be shortened)

### ISSUE THREAD

**Issue by xizar** [emersonrp/bindcontrol#14] opened 2024-05-10 03:03 UTC
On startup, the window covers the full height of my desktop (1440p resolution) and refuses to allow itself to be shortened.  This creates a lot of wasted space (roughly 1/5 of the vertical space) and also makes it frustrating to move around, as the "write binds" button is at the bottom of the window making it inaccessible if I reposition the window so it sits lower on the screen.

**Comment by emersonrp** [comment] 2024-05-10 19:21
Is this on Windows?  What versions of Python and wxPython are you using?  I'll see if I can reproduce this.  The window does have a minimum size, but I thought I'd arranged it so that it was vertically short enough for most resolutions, 1440 included.

I can experiment again with allowing the window to be manually resized smaller, but the interaction of the tabs and the resulting scroll bars has historically ended up very klunky and typically instantiated the window at a weird size at startup.

I have also mulled the idea of adding a menu item to write binds in addition to the button, just for convenience's sake.

Thanks, I'll look into this!

**Comment by xizar** [comment] 2024-05-10 21:18
I apologize for not including more info.  This is on Windows 10.  I have reproduced this behaviour with Python 3.7.7 (which I didn't realize is what I had before) and Python 3.12.3.  I don't know what version (if any?) of wxpython I had installed with 3.7.7, but I had pip install wxpython and now wx.version() returns '4.2.1 msw (phoenix) wxWidgets 3.2.2.1'

I've attached a screenshot to show the white space proportions.  As it is right now, it's not unusable, it's just very inconvenient.

![BindControl_QlEmKwoZq2](https://github.com/emersonrp/bindcontrol/assets/5367098/a3bd0989-ffc0-4e17-8c7b-095677c18399)

**Comment by emersonrp** [comment] 2024-05-17 22:28
Oh yeah that's huge. If you get a minute, can you check the other tabs? It's supposed to "shrink wrap" to fit, so probably one of the other tabs (probably the Mastermind one) is actually that big.  I've been mulling ways to compact it, or maybe split it into two tabs. If it's the problem, I can focus on that as a way forward.

**Comment by xizar** [comment] 2024-05-18 00:12
The window stays at that same fixed height for all tabs with varying amounts of empty whitespace.  For example, on "Custom Binds", there is a single row with "new simple bind new complex bind new buffer bind" buttons at the very top and essentially a fully blank page below until the "Write Binds" button at the bottom.

**Comment by emersonrp** [comment] 2024-05-18 20:07
Oh yeah, no, sorry, I meant check and see whether one of the other tabs seems to "fit" the large window, because the window's initial size is supposed to shrink-to-fit the tab with the largest contents.  I was thinking either the Mastermind tab or the left column of the Movement Powers tab is what is causing the extra height, and was going to look into re-laying-out whatever the culprit is.  The Custom Binds tab, if there are no binds in there, yeah is gonna be an ocean of empty space.

**Comment by xizar** [comment] 2024-05-18 20:58
The SoD, InspPopper and MM tab content seem to occupy roughly the same length of page, while still leaving a fifth to a quarter of the page empty.

**Comment by emersonrp** [comment] 2024-05-19 16:32
OK I can now reproduce this in my Windows 10 VM set to 1920x1440.  Weird that it has such a wrong idea about the minimum necessary vertical size.  I have a few ideas and I'm tinkering with them now.

**Comment by emersonrp** [comment] 2024-05-19 20:56
OK, I have released 0.14.1, which allows for arbitrarily resizing the window, as well as a preference (true by default) to save its size and position between runs.  Please let me know your luck with this.

Check the release notes:  https://github.com/emersonrp/bindcontrol/releases/tag/v0.14.1

**Comment by xizar** [comment] 2024-05-19 21:12
Were this a gag I came up with, I would be incredibly proud, however: 

![BindControl_uBPvL3IW9b](https://github.com/emersonrp/bindcontrol/assets/5367098/5e2fdb3c-6e7a-4611-95b8-79b29923a7ce)

This is all that shows up when I run it.

If there is a configuration file, I have not found it to try to clear settings.

**Comment by emersonrp** [comment] 2024-05-19 21:23
Yeah, glad you figured out the part where it's still got a drag handle.  That's exactly the thing I was talking about in the last sentence of the release note.  So it wasn't just me and I need to figure that out because it's possible everyone on Windows will have that experience first run, which ugh.

And yeah, I didn't fix the part where it has a terrible idea about the vertical space, which may take some deep tinkering one tab at a time, but I hope to.  Making it resizable was just a workaround to make it less inconvenient to work with in the short to medium term.

Leaving this open until I get that misbehavior tamed.

**Comment by emersonrp** [comment] 2024-05-19 22:23
I have tamed that misbehavior -- yeah, on first run in Windows, the app would try to resize itself to 0 x 0 pixels, leading to that tiny window.  This has been fixed in 0.14.2.1.

If you wanted to test it yourself, you could stash away or delete the BindControl INI file, which should be at %HOME%\AppData\Roaming\BindControl.ini, to simulate a first run.  It should just open up at the "normal" too-large size it always has and then remember its size and position from then on.

https://github.com/emersonrp/bindcontrol/releases/tag/v0.14.2.1

**Comment by emersonrp** [comment] 2024-05-20 17:48
I've done some woodshedding and discovered the general reason it's thinking the vertical space needs to be so large.

Most of the problem lies in the Movement Powers tab, where it's allocating space vertically for all of the control groups for, like, jump powers or teleport powers, even if they are not enabled and visible.  This includes controls for schemes that have been laid out but not completely implemented yet, like temp travel powers and kheldian movement powers.  There's a big handful of those boxes and they're all being part of the space of the layout despite my early efforts.  (The layout / spacing / sizing scheme for wxWindows is incredibly flexible, and therefore also cryptic and fiddly.)

I have some thoughts on how to get it not to do that, but basically the Movement Power tab has wanted a rethink and redesign for a while.  I'm going to try out a few ideas and see if I can get it to be less ugly and asymmetric and sprawling.

**Comment by emersonrp** [comment] 2024-06-13 21:17
This is finally fixed, at least as far as it can be, in v0.18.1.  The Movement Powers tab still needs some revisiting, but the extra ocean of vertical space at the bottom of the app has been ameliorated significantly.  Closing this issue.

https://github.com/emersonrp/bindcontrol/releases/tag/v0.18.1

**Closed by emersonrp** 2024-06-13 21:17 UTC
Labels: enhancement
