### ISSUE TITLE
Mystic Flight is totally borked (0.14.2.1)

### ISSUE THREAD

**Issue by xizar** [emersonrp/bindcontrol#20] opened 2024-05-21 05:27 UTC
SoD bindings to use Mystic Flight as a flight power are currently unusable.

Enabling SoD Flight with Mystic Flight will make the character jump nonstop or *might* actually turn on Mystic Flight, and then you soar into the heavens.  Moving in any of the three dimensions turns off the behaviour of flying straight up (tangent: I remember this being an optional setting in SoD), and you can fly around or teleport without issues.

Hitting "F" to toggle Mystic Flight off does not toggle it off, but sets you to soaring straight up as described above (though, since MF is already active, there's no jumping).

I believe Mystic Flight worked fine prior to 0.14, though I hadn't played my Sorcery toons much since restarting playing a few weeks ago.  (edited to correct version from 0.4.14...  I got over enthusiastic with my 4s.)

**Comment by emersonrp** [comment] 2024-05-21 18:30
Not sure which version you were intending to say with "0.4.14" -- just 0.14 maybe?  I'll look into what might have changed with Mystic Flight specifically between 0.13 and 0.14.  I'm speccing a toon into Mystic Flight now to work on this and possibly the Translocation stuff in conjunction with the rest of the teleport rethink.

If you feel inspired, you could check historical releases and see if indeed it works as you expect back in 0.13.6, which was the last 0.13 release.  No worries if not, I'll get to that myself eventually.

It sort of sounds like it's not necessarily loading one of the bind files when it's supposed to.  Does the chat window have any errors that reflect that?

**Comment by xizar** [comment] 2024-05-21 23:03
While 13.6 still has the bug from https://github.com/emersonrp/bindcontrol/issues/15 it otherwise behaves as expected once Hover is removed from a possibility (setting a pool power to flight, makign sure Hover's box is unticked under Flight in SoD, then removing Flight from the power pools).

**Comment by emersonrp** [comment] 2024-05-22 00:50
I can't reproduce this.  Bug #15 absolutely is there, and I'm still looking into that, but I'm not getting any weird jumping / constant upward behavior like you describe with 0.14.  Can you attach the profile you're using?

**Comment by xizar** [comment] 2024-05-22 01:50
[LaTina - Copy.txt](https://github.com/emersonrp/bindcontrol/files/15397058/LaTina.-.Copy.txt)

I changed the file extension so github would let me upload it here.

I've deleted the bind folder and cleared all my keybinds in-game and she still acts wonky after writing a fresh set of binds.

**Comment by emersonrp** [comment] 2024-05-22 18:26
OK yes with your profile I get the same behavior you describe.  Fascinating.  I am on it.  One thing I noticed, can you confirm whether when you "Write Binds" the subsequent dialog says there was 1 error?

**Comment by emersonrp** [comment] 2024-05-22 19:46
OK yes it is trying to initiate "blast off" and BindControl has not written all the necessary bind files to make that work.  It's specifically looking for BO/BO000000.txt at the point of initially hitting the "Flight Mode" key, and the whole BO tree is not being generated by this config, which is probably the core of the bug.

This brings up the question, though: what is the desired behavior?

The initial motivation behind the SoD binds, back in 2004-5 when Gnarly released his initial code for this, was to toggle between, for instance, Flight and Hover, in order to realize the endurance savings and automagically get the defense bonus when not moving.  With no "Hover" to toggle to, what would be the right thing to be doing with movement binds?  Surely not switch off Mystic Flight when you stop moving, you'd fall out of the sky.

So what is BindControl's role here?  Should the "Flight Mode" key just be a simple toggle for Mystic Flight (or Flight), if Hover is not available?  It seems like the full SoD tangle is more trouble than it's worth in the case where we don't have an alternate "non-speed" travel power to switch to when not moving.

Thoughts?  Anyone?

**Comment by xizar** [comment] 2024-05-22 20:24
With regard specifically to Mystic Flight, switching to Hover would not be a good idea, as the Translocate may be done while the character is hovering (not the power, just sitting there).  There would be value in simply *activating* hover for the flight control it offers (Mystic Flight feels about as drifty as Flight/Fly).

(as a side thought, I wonder if there could be an "Evasive Maneuvers" mode where you stop switching between Hover and Fly (with a keybinding to switch between EM and Hover modes).  While it's unlikely someone is running Mystic Flight *and* Evasive Maneuvers, an EM mode for Mystic Flight could also be useful.)

**Comment by emersonrp** [comment] 2024-05-22 20:58
That all makes sense.  I'm starting to think that trying to incorporate Mystic Flight into the SoD tangle as an alternative to Flight is not the right path;  that instead it wants its own set of logic altogether.  "Turn on and off with the flight mode key, optionally activate hover when stopped" and then maybe Translocation can use the new still-hypothetical teleport logic.

I think with respect to Blast Off, the right thing would be to make it work instead of removing it.  I know I have ever used it and enjoy it when it works, but if it continues to cause problems with people who (quite reasonably) just tap the "flight mode" key quickly, I may rethink.

**Comment by emersonrp** [comment] 2024-05-22 22:16
I've just released v0.14.4.1, which contains a quick fix to write the missing BO files even if Hover is not available.

This fixes the jump / launch weirdness.  The current behavior is that the Flight Mode key operates as "blast off," launching upward while initially held down and then stopping when released.  Currently togging off flight mode midair will -drop you out of the sky- so this is probably a partial fix.

Let me know how this behaves for you.

https://github.com/emersonrp/bindcontrol/releases/tag/v0.14.4.1

**Comment by emersonrp** [comment] 2024-05-23 20:30
I'm closing this as I believe v0.14.4.1 fixes the borkedness described.  If you still have problems with this specifically, please comment and re-open it.  New or different borkedness, please open a new issue.  Thanks!

**Closed by emersonrp** 2024-05-23 20:30 UTC
