### ISSUE TITLE
Renaming Binds needs to rename all associated Ctrls.

### ISSUE THREAD

**Issue by autobotcoop** [emersonrp/bindcontrol#32] opened 2024-06-02 21:38 UTC
![image](https://github.com/emersonrp/bindcontrol/assets/39393574/f18db03a-4d59-4656-874d-f641edeb9960)

Would like to be able to edit these.

**Comment by emersonrp** [comment] 2024-06-02 21:47
Yeah, it had occurred to me that people might ever want to do that. That spot can't be made directly editable due to limitations of the wx toolkit, but I could add in a "rename" button and a tiny dialog for that. Apart from the ui considerations, that should be pretty easy to do.

**Comment by autobotcoop** [comment] 2024-06-02 22:16
What about little unlock/locked icons?

**Comment by emersonrp** [comment] 2024-06-02 22:27
Is that a separate thought?  Like, to lock the bind against being changed?  That's a little more complicated but certainly possible.

**Comment by autobotcoop** [comment] 2024-06-02 22:31
I think what I'm think of is something like this. 

Bind Name (locked, indicated with a clickable icon to toggle): Can't change 
Bind Name (unlocked, indicated with a clickable icon to toggle): Changeable 

I think that keep the UI clean.

**Comment by emersonrp** [comment] 2024-06-02 22:50
The issue is that the spot where the name lives can't be made directly editable in-place.  It just can't, the toolkit won't allow it.  So there's no notion of being able to lock or unlock it.  It needs to present a separate UI element that is editable, a little text field or something, in order to be able to take input at all.

I'm mocking up a scheme where there's a separate button below the "delete bind" button for "rename bind" that will re-show the tiny dialog that appears when you first name a new bind, and let you rename it there.  I think it'll be unobtrusive enough, as well as being sorta familiar since it's the same exact dialog you already saw when you made the bind.  I'll finish pulling this together and make a prerelease to try it out.

**Comment by autobotcoop** [comment] 2024-06-02 22:52
Thanks for explaining it to me in detail. 🙂

**Comment by emersonrp** [comment] 2024-06-03 01:40
Version 0.17.5 now has a little "rename bind" button, marked "#", beneath the "delete bind" button.  Seems to work well.  Let me know your luck.

https://github.com/emersonrp/bindcontrol/releases/tag/v0.17.5

**Comment by autobotcoop** [comment] 2024-06-03 04:12
![image](https://github.com/emersonrp/bindcontrol/assets/39393574/c81a28d0-1fe9-45c6-9cce-4089a042b86e)

First Attempt to go from Test -> Helper

Minimizing the window and then maximizing it cleared it.

**Comment by emersonrp** [comment] 2024-06-03 04:53
Ah yeah I see that now.  Also found a bug where building a new custom bind breaks.  Will release a fix to both soon, along with some other work.

**Comment by emersonrp** [comment] 2024-06-03 05:05
Released 0.17.6, which has a fix for that display badness on Windows, as well as other features.  Check it out.

https://github.com/emersonrp/bindcontrol/releases/tag/v0.17.6

**Comment by emersonrp** [comment] 2024-06-07 17:01
Leaving this open, as I think I need to work on the Deep Innards to twiddle the actual CtrlNames to match the changed name of the bind.  This should be a little tedious to implement but pretty straightforward and somewhat necessary.

**Comment by emersonrp** [comment] 2024-06-12 01:36
This has been implemented, and will be released as part of the major Ctrls overhaul in v0.18, whenever that happens.

**Comment by emersonrp** [comment] 2024-06-12 21:00
This has shipped with v0.18

https://github.com/emersonrp/bindcontrol/releases/tag/v0.18

**Closed by emersonrp** 2024-06-12 21:00 UTC
Labels: bug
